---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: harbor
  targetNamespace: harbor
  chart:
    repository: https://helm.goharbor.io
    name: harbor
    version: v1.1.1
  values:
    expose:
      tls:
        enabled: true
        secretName: ingress-cert-${LETSENCRYPT_ENVIRONMENT}
      type: clusterIP
    externalURL: https://harbor.${MY_DOMAIN}
    # kics-scan ignore-line
    harborAdminPassword: admin
    persistence:
      enabled: false
